on:
  workflow_call:
    inputs:
      params-file:
        type: string
        required: true
      resource-group-name:
        type: string
        required: true
    secrets:
      azure-credentials:
        required: true
      azure-subscription-id:
        required: true
      repository-token:
        required: true

name: Azure Bicep - Base
jobs:
  build-and-deploy:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@master

        # Log into Azure
      - name: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.azure-subscription-id }}
          resourceGroupName: ${{ inputs.resource-group-name }}
          template: ./infra/main.bicep
          parameters: ${{ inputs.params-file }}
          failOnStdErr: false
