on:
  push:
    branches:
      - master
    paths:
      - "infra/**/*.bicep"
      - "infra/**/*.json"
      - "infra/**/*.ps1"
      - "core/**/*.bicep"
      - ".github/workflows/learnnx-deploy-bicep-base.yml"

name: Azure Bicep - Dev
jobs:
  deploy-bicep-script:
    uses: ./.github/workflows/learnnx-deploy-bicep-base.yml
    with:
      params-file: "./infra/paramsDev.json"
      resource-group-name: "development-ming"
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS_DEVELOPMENT_MING_DEV }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      repository-token: ${{ secrets.REPOSITORY_TOKEN }}
