name: LearnNx web static app - Test

on:
  push:
    branches:
      - test
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - test

permissions:
  contents: read

jobs:
  setup-static-web-app:
    uses: ./.github/workflows/learnnx-azure-static-web-base.yml
    with:
      app-location: 'react'
      app-artifact-location: 'dist/apps/regi'
      app-build-command: 'npx nx run mingzsite:build --mode test'
    secrets:
      token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_TEST }}
    permissions:
      pull-requests: write
      contents: read

  setup-storybook-static-web-app:
    uses: ./.github/workflows/learnnx-azure-static-web-base.yml
    with:
      app-location: 'react'
      app-artifact-location: 'dist/storybook/shared-ui'
      app-build-command: 'npx nx run shared-ui:build-storybook'
    secrets:
      # Where is this token? The static web app development token.
      token: ${{ secrets.AZURE_STATIC_WEB_APPS_STORYBOOK_API_TOKEN_PROD }}
    permissions:
      pull-requests: write
      contents: read
