on:
  push:
    branches:
      - dev
    paths:
      - 'infra/**/*.bicep'
      - 'infra/**/*.json'
      - 'infra/**/*.ps1'
      - 'core/**/*.bicep'
      - '.github/workflows/learnnx-deploy-bicep-base.yml'

name: Azure Bicep - Dev
jobs:
  deploy-bicep-script:
    uses: ./.github/workflows/learnnx-deploy-bicep-base.yml
    with:
      params-file: './infra/paramsDev.json'
      # the resource group name should be replace with *-Dev, *-Test, *-Dev
      # e.g: app-dev
      resource-group-name: 'development-ming'
    secrets:
      # This AZURE_CREDENTIALS_DEVELOPMENT_MING is coming from app registration ==> <Deployment Account>
      # You can test this secret with command: az login --service-principal -u <app-id> -p <-secrets> --tenant <tenant>
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS_DEVELOPMENT_MING }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      repository-token: ${{ secrets.REPOSITORY_TOKEN }}
