on:
  workflow_call:
    inputs:
      params-file:
        type: string
        required: true
      resource-group-name:
        type: string
        required: true
    secrets:
      azure-credentials:
        required: true
      azure-subscription-id:
        required: true
      repository-token:
        required: true

name: Azure Bicep - Base
jobs:
  build-and-deploy:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@master

      # Log into Azure with 
      # The Azure credentials is coming from app registration ==> <Deployment Account>
      # You can test this secret with command: az login --service-principal -u <app-id> -p <-secrets> --tenant <tenant>
      # To setup the new credentials, you can use this command:
      # az ad sp create-for-rbac --name "<group>" --role contributor --scopes /subscriptions/<###-###-###>/resourceGroups/<yourGroup> --sdk-auth
      # Then Save the output to GitHub Secrets
      # More docs: https://github.com/Azure/actions-workflow-samples/blob/master/assets/create-secrets-for-GitHub-workflows.md

      - name: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.azure-credentials }}

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.azure-subscription-id }}
          resourceGroupName: ${{ inputs.resource-group-name }}
          template: ./infra/main.bicep
          parameters: ${{ inputs.params-file }}
          failOnStdErr: false
