# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript

name: LearnNx web static app - Base

on:
  workflow_call:
    inputs:
      app-location: 
        required: true
        type: string
      app-artifact-location: 
        required: true
        type: string
      app-build-command:
        required: true
        type: string
    secrets:
      token: 
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:     
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build And Deploy Dev
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # secret containing deployment token for static web app
          azure_static_web_apps_api_token: ${{ secrets.token }} 
          # I don't think this is needed?
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ${{ inputs.app-location }}
          app_artifact_location: ${{ inputs.app-artifact-location }}
          output_location: ${{ inputs.app-artifact-location }}
          app_build_command: ${{ inputs.app-build-command }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    permissions:
      contents: none
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          # secret containing api token for app
          azure_static_web_apps_api_token: ${{ secrets.token }}
          action: "close"
